fail-on-severity: moderate 

comment-summary-in-pr: always 

allow-licenses: 
  - MIT
  - GPL-3.0
  - BSD-3-Clause
  - Apache-2.0
  - ISC

deny-licenses: 
  - LGPL-2.0
  - BSD-2-Clause

allow-ghsas: 
  - GHSA-abcd-1234-5679
  - GHSA-efgh-1234-5679

fail-on-scopes: 
  - development
  - runtime
  - unknown